version: "3.8"
services:

  database:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./migrations/000001_create_tables.up.sql:/docker-entrypoint-initdb.d/create_tables.sql